---
title: 'Discrete Mathematics #4'
author: "20192208 김형훈"
categories: ["work"]
format: 
  pdf:
    documentclass: report
    papersize: a4
    number-sections: true
    number-depth: 3
    top-level-division: section
    fontsize: 17pt
    geometry:
      - top=20mm
include-in-header: 
  text: |
    \usepackage{fontspec}
    \setmainfont{Noto Sans KR}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{}{0pt}{\huge}
    \titleformat{\section}[block]{\normalfont\Large\bfseries}{}{0pt}{}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{-3pt}{0pt}{10pt}
    \titlespacing*{\section}{0pt}{20pt}{10pt}
    \newcommand{\sectionbreak}{\clearpage}
    \usepackage{setspace}
    \setstretch{1.8}
    \usepackage{tabularx}
    \newcolumntype{Y}{>{\centering\arraybackslash}X}
execute:
  echo: false
  warning: false
  message: false
---

# 8.2

## Problem 4

### a

$r^2 - r + 6 = 0$  
$(r-3)(r+2) = 0$  
$r = 3, -2$  
$a_n = c_1 3^n + c_2 (-2)^n$  
$a_0 = 3 = c_1 + c_2$  
$a_1 = 6 = 3c_1 - 2c_2$  
$c_1 = 2, c_2 = 1$  
∴ $a_n = 2(3^n) + (-2)^n$

### b

$r^2 - 7r + 10 = 0$  
$(r-5)(r-2) = 0$  
$r = 5, 2$  
$a_n = c_1 5^n + c_2 2^n$  
$a_0 = 2 = c_1 + c_2$  
$a_1 = 1 = 5c_1 + 2c_2$  
$c_1 = -1, c_2 = 3$  
∴ $a_n = -5^n + 3(2^n)$

### c

$r^2 - 6r + 8 = 0$  
$(r-4)(r-2) = 0$  
$r = 4, 2$  
$a_n = c_1 4^n + c_2 2^n$  
$a_0 = 4 = c_1 + c_2$  
$a_1 = 10 = 4c_1 + 2c_2$  
$c_1 = 1, c_2 = 3$  
∴ $a_n = 4^n + 3(2^n)$

### d

$r^2 - 2r + 1 = 0$  
$(r-1)^2 = 0$  
$r = 1$  
$a_n = c_1 + c_2n$
$a_0 = 4 = c_1$  
$a_1 = 1 = c_1 + c_2$  
$c_1 = 4, c_2 = -3$  
∴ $a_n = 4 - 3n$

### e

\vspace{0.7em}
$a_n = \begin{cases}
  5 & \text{if n is even} \\
  -1 & \text{if n is odd}
\end{cases}$
\vspace{0.7em}

### f

$r^2 + 6r + 9 = 0$  
$(r+3)^2 = 0$  
$r = -3$  
$a_n = c_1 (-3)^n + c_2 n(-3)^n$  
$a_0 = 3 = c_1$  
$a_1 = -3 = -3c_1 - 3c_2$  
$c_1 = 3, c_2 = 0$  
∴ $a_n = 3(-3)^n$

### g

$r^2 + 4r - 5 = 0$  
$(r+5)(r-1) = 0$  
$r = -5, 1$  
$a_n = c_1 (-5)^n + c_2 (1)^n$  
$a_0 = 2 = c_1 + c_2$  
$a_1 = 8 = -5c_1 + c_2$  
$c_1 = -1, c_2 = 3$  
∴ $a_n = -(-5)^n + 3$

# 8.3

$f(3^k) = 2^kf(1) + \Sigma_{i=0}^{k-1} 2^i 3^{2(k-i)}$  

## Problem 12

$f(n) = 2f(\frac{n}{3}) + 4$  
$f(3^k) = 2f(3^{k-1}) + 4$
$f(3^{k-1}) = 2f(3^{k-2}) + 4$  
$f(3^k) = 2(2f(3^{k-2}) + 4) + 4 = 4f(3^{k-2}) + 12$  
$f(3^k) = 2^kf(1) + 4\Sigma_{i=0}^{k-1} 2^i$  
$f(3^k) = 2^k + 4(2^k - 1)$  
$f(3^k) = 5(2^k) - 4$

## Problem 13

$n = 3^k$, $k = \log_3 n$  
$f(n) = 5(2^{\log_3 n}) - 4$  
$O(2^{\log_3 n}) = O(n^{\log_3 2}) = O(n^{0.63})$

## Problem 22

### a
$f(16) = 2f(4)\log 16$  
$f(4) = 2f(2)\log 4 = 2 * 1 * 2 = 4$  
$f(16) = 2 * 4 * 4 = 32$

### b

$f(n) = 2f(\sqrt{n})\log n$  
$n = 2^m, m = \log n$  
$f(2^m) = 2f(2^{\frac{m}{2}})\log 2^m$  
$g(m) = f(2^m)$  
$g(m) = 2g(\frac{m}{2})m$  
$f(n) = O(m^2) = O((\log n)^2)$

# 8.4

## Problem 24

### a

$y_1 = x_1 - 3, y_1 ≥ 0$  
$G_1(z) = z^3(1 + z + z^2 + z^3 + ...) = \frac{z^3}{1-z}$  
$G_2(z) = z(1 + z + z^2 + z^3 + z^4 + z^5) = z\frac{1-z^5}{1-z}$  
$G_3(z) = 1 + z + z^2 + z^3 + z^4 = \frac{1-z^5}{1-z}$  
$G_4(z) = z + z^2 + z^3 + ... = \frac{z}{1-z}$  
$G(z) = G_1(z)G_2(z)G_3(z)G_4(z) = \frac{z^3}{1-z} \frac{z(1-z^5)}{1-z} \frac{1-z^5}{1-z} \frac{z}{1-z} = \frac{z^5(1-z^5)^2}{(1-z)^4}$

### b

$G(z) = \frac{z^5(1-z^5)^2}{(1-z)^4} = \frac{z^5-2z^{10}+z^{15}}{(1-z)^4}$  
$\frac{z^5}{(1-z)^4}, z^2 \text{ from } \frac{1}{(1-z)^4}, \binom{5}{3} = 10$  
$\frac{-2z^{10}}{(1-z)^4}, z^{-3} \text{ from } \frac{1}{(1-z)^4}, \text{ none}$  
$\frac{z^{15}}{(1-z)^4}, z^{-8} \text{ from } \frac{1}{(1-z)^4}, \text{ none}$  
$a_7 = 10$

## Problem 34

$A(z) = a_0 + a_1z + a_2z^2 + ...$  
$a_k = 7^ka_0, A(Z) = 5 + 5(7z) + 5(7z)^2 + ...$  
$A(z) = 5(1 + 7z + 7^2z^2 + ...) = \frac{5}{1-7z}$  
$a_k = 5(7^k)$

## Problem 36

$A(z) = 3zA(z) + z\Sigma_{k=0}^{∞} (4z)^k$  
$A(z) = 3zA(z) + \frac{z}{1-4z}$  
$A(z) = \frac{z}{(1-3z)(1-4z)}$
