---
title: OR 과제 - 3
subtitle: 20192208 김형훈
categories: ["보고서", "OR"]
date: last-modified
format: 
  pdf:
    fig-pos: 'H'
    fig-width: 6
    fig-height: 4
    documentclass: report
    papersize: a4
    top-level-division: chapter
    fontsize: 17pt
    toc: false
    geometry:
      - top=20mm
    indent-size: 2
include-in-header: 
  text: |
    \date{}
    \usepackage{fontspec}
    \setmainfont{Noto Sans KR}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{\thechapter.}{0.8em}{\huge}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{0pt}{-20pt}{5pt}
    \titlespacing*{\section}{0pt}{10pt}{10pt}
    \newcommand{\chapterbreak}{\clearpage}
    \usepackage{setspace}
    \setstretch{1.5}
    \usepackage{tabularx}
    \newcolumntype{Y}{>{\centering\arraybackslash}X}
    \usepackage[bottom]{footmisc}
    \usepackage{setspace}
    \renewcommand{\footnotesize}{\setstretch{1.2}\fontsize{9pt}{11pt}\selectfont}
    \setlength{\skip\footins}{10pt}
    \setlength{\footnotesep}{8pt}
    \renewcommand{\footnoterule}{\vspace{1em}\hrule width 0.5\linewidth\vspace{1em}}
    \makeatletter
    \renewcommand{\@makefntext}[1]{\noindent\makebox[1.5em][r]{\@makefnmark}\hspace{0.5em}#1}
    \makeatother
    \usepackage{float}
    \usepackage{multirow}
    \usepackage{booktabs}

execute:
  echo: false
  warning: false
  message: false

---

# 4.6-2

수식을 다시 재구성해보면 아래와 같다.

$$
\begin{aligned}
\text{Maximize} \quad & Z - 4x_1 - 2x_2 - 3x_3 - 5x_4 + M\bar{x}_5 + M\bar{x}_6 = 0 \\
\text{Subject to} \quad & 2x_1 + 3x_2 + 4x_3 + 2x_4 + \bar{x}_5 = 300\\
& 8x_1 + x_2 + x_3 + 5x_4 + \bar{x}_6 = 300 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4 \\
& \bar{x}_5 ≥ 0, \bar{x}_6 ≥ 0
\end{aligned}
$$

## a

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & -4 & -2 & -3 & -5 & M & M & 0 \\
\bar{x}_5 & 0 & 2 & 3 & 4 & 2 & 1 & 0 & 300 \\
\bar{x}_6 & 0 & 8 & 1 & 1 & 5 & 0 & 1 & 300 \\
\hline
\end{array}
$$

basic 변수가 0이 되도록 다시 계산해준다.

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & -4 - 10M & -2 - 4M & -3 - 5M & -5 - 7M & 0 & 0 & -600M \\
\bar{x}_5 & 0 & 2 & 3 & 4 & 2 & 1 & 0 & 300 \\
\bar{x}_6 & 0 & 8 & 1 & 1 & 5 & 0 & 1 & 300 \\
\hline
\end{array}
$$

- 초기 BFS: (0, 0, 0, 0, 300, 300)
- 초기 진입 변수: $x_1$
- 초기 퇴출 변수: $\bar{x}_6$

## b

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & 0 & -\frac{3}{2} - \frac{11}{4}M & -\frac{5}{2} - \frac{15}{4}M & -\frac{5}{2} - \frac{3}{4}M & 0 & \frac{1}{2} + \frac{5}{4}M & 150-225M \\
\bar{x}_5 & 0 & 0 & \frac{11}{4} & \frac{15}{4} & \frac{3}{4} & 1 & -\frac{1}{4} & \frac{900}{4} \\
x_1 & 0 & 1 & \frac{1}{8} & \frac{1}{8} & \frac{5}{8} & 0 & \frac{1}{8} & \frac{300}{8} \\
\hline
\end{array}
$$

- 진입 변수: $x_3$
- 퇴출 변수: $\bar{x}_5$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & 0 & \frac{1}{3} & 0 & -2 & \frac{2}{3} + M & \frac{1}{3} + M & 300 \\
x_3 & 0 & 0 & \frac{11}{15} & 1 & \frac{1}{5} & \frac{4}{15} & -\frac{1}{15} & 60 \\
x_1 & 0 & 1 & \frac{1}{30} & 0 & \frac{3}{5} & -\frac{1}{30} & \frac{2}{15} & 30 \\
\hline
\end{array}
$$

- 진입 변수: $x_4$
- 퇴출 변수: $x_1$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & \frac{10}{3} & \frac{4}{9} & 0 & 0 & \frac{5}{9} + M & \frac{7}{9} + M & 400 \\
x_3 & 0 & -\frac{1}{3} & \frac{13}{18} & 1 & 0 & \frac{5}{18} & -\frac{1}{9} & 50 \\
x_4 & 0 & \frac{5}{3} & \frac{1}{18} & 0 & 1 & -\frac{1}{18} & \frac{2}{9} & 50 \\
\hline
\end{array}
$$

종료.

- $x_1$ = 0
- $x_2$ = 0
- $x_3$ = 50
- $x_4$ = 50
- $x_5$ = 0
- $x_6$ = 0
- $Z$ = 400

## c

$$
\begin{aligned}
\text{Minimize} \quad & Z - \bar{x}_5 - \bar{x}_6 = 0 \\
\text{Subject to} \quad & 2x_1 + 3x_2 + 4x_3 + 2x_4 + \bar{x}_5 = 300\\
& 8x_1 + x_2 + x_3 + 5x_4 + \bar{x}_6 = 300 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4 \\
& \bar{x}_5 ≥ 0, \bar{x}_6 ≥ 0
\end{aligned}
$$

Minimize를 Maximize로 바꿔주자.

$$
\begin{aligned}
\text{Maximize} \quad & -Z + \bar{x}_5 + \bar{x}_6 = 0 \\
\text{Subject to} \quad & 2x_1 + 3x_2 + 4x_3 + 2x_4 + \bar{x}_5 = 300\\
& 8x_1 + x_2 + x_3 + 5x_4 + \bar{x}_6 = 300 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4 \\
& \bar{x}_5 ≥ 0, \bar{x}_6 ≥ 0
\end{aligned}
$$

표로 작성하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 0 \\
\bar{x}_5 & 0 & 2 & 3 & 4 & 2 & 1 & 0 & 300 \\
\bar{x}_6 & 0 & 8 & 1 & 1 & 5 & 0 & 1 & 300 \\
\hline
\end{array}
$$

basic 변수를 0이 되도록 다시 계산하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & -10 & -4 & -5 & -7 & 0 & 0 & -600 \\
\bar{x}_5 & 0 & 2 & 3 & 4 & 2 & 1 & 0 & 300 \\
\bar{x}_6 & 0 & 8 & 1 & 1 & 5 & 0 & 1 & 300 \\
\hline
\end{array}
$$

자 이제 표를 완성해보자.

- 진입변수: $x_1$
- 퇴출변수: $\bar{x}_6$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & 0 & -\frac{11}{4} & -\frac{15}{4} & -\frac{3}{4} & 0 & \frac{5}{4} & -225 \\
\bar{x}_5 & 0 & 0 & \frac{11}{4} & \frac{15}{4} & \frac{3}{4} & 1 & -\frac{1}{4} & 225 \\
x_1 & 0 & 1 & \frac{1}{8} & \frac{1}{8} & \frac{5}{8} & 0 & \frac{1}{8} & \frac{75}{2} \\
\hline
\end{array}
$$

- 진입변수: $x_3$
- 퇴출변수: $\bar{x}_5$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & \bar{x}_6 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 0 \\
x_3 & 0 & 0 & \frac{11}{15} & 1 & \frac{1}{5} & \frac{4}{15} & -\frac{1}{15} & 60 \\
x_1 & 0 & 1 & \frac{1}{30} & 0 & \frac{3}{5} & -\frac{1}{30} & \frac{2}{15} & 30 \\
\hline
\end{array}
$$

Phase 1 종료.

이제 필요없는 인공변수를 제거하고, 기존의 obj를 가져와서 다시 표를 만들어보자.

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 &\text{RHS} \\
\hline
 & 1 & -4 & -2 & -3 & -5 & 0 \\
x_3 & 0 & 0 & \frac{11}{15} & 1 & \frac{1}{5} & 60 \\
x_1 & 0 & 1 & \frac{1}{30} & 0 & \frac{3}{5} & 30 \\
\hline
\end{array}
$$

basic 변수를 0으로 만들어주자.

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 &\text{RHS} \\
\hline
 & 1 & 0 & \frac{1}{3} & 0 & -2 & 300 \\
x_3 & 0 & 0 & \frac{11}{15} & 1 & \frac{1}{5} & 60 \\
x_1 & 0 & 1 & \frac{1}{30} & 0 & \frac{3}{5} & 30 \\
\hline
\end{array}
$$

- 초기 BFS($x_1, x_2, x_3, x_4$): (30, 0, 60, 0)
- 초기 진입변수: $x_4$
- 초기 퇴출변수: $x_1$

# 4.6-3

## a

$$
\begin{aligned}
\text{Maximize} \quad & -Z = -2x_1 - 3x_2 - x_3 - M\bar{x}_5 - M\bar{x}_7 \\
\text{Subject to} \quad & x_1 + 4x_2 + 2x_3 - x_4 + \bar{x}_5 = 8 \\
& 3x_1 + 2x_2 - x_6 + \bar{x}_7 = 6 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 6 \\
& \bar{x}_5 ≥ 0, \bar{x}_7 ≥ 0
\end{aligned}
$$

## b

먼저 basic 변수를 0으로 만들어주자.

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & 2 - 4M & 3 - 6M & 1 - 2M & M & 0 & M & 0 & -14M \\
\bar{x}_5 & 0 & 1 & 4 & 2 & -1 & 1 & 0 & 0  & 8 \\
\bar{x}_7 & 0 & 3 & 2 & 0 & 0 & 0 & -1 & 1 & 6 \\
\hline
\end{array}
$$

- 진입변수: $x_2$
- 퇴출변수: $\bar{x}_5$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & \frac{5}{4} - \frac{5}{2}M & 0 & M - \frac{1}{2} & \frac{3}{4} - \frac{1}{2}M & \frac{3}{2}M - \frac{3}{4} & M & 0 & -2M - 6 \\
x_2 & 0 & \frac{1}{4} & 1 & \frac{1}{2} & -\frac{1}{4} & \frac{1}{4} & 0 & 0  & 2 \\
\bar{x}_7 & 0 & \frac{5}{2} & 0 & -1 & \frac{1}{2} & -\frac{1}{2} & -1 & 1 & 2 \\
\hline
\end{array}
$$

- 진입변수: $x_1$
- 퇴출변수: $\bar{x}_7$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & \frac{1}{2} & M - \frac{1}{2} & \frac{1}{2} & M - \frac{1}{2} & -7 \\
x_2 & 0 & 0 & 1 & \frac{3}{5} & -\frac{3}{10} & \frac{3}{10} & \frac{1}{10} & -\frac{1}{10}  & \frac{9}{5} \\
x_1 & 0 & 1 & 0 & -\frac{2}{5} & \frac{1}{5} & -\frac{1}{5} & -\frac{2}{5} & \frac{2}{5} & \frac{4}{5} \\
\hline
\end{array}
$$

종료.

- $x_1$ = $\frac{4}{5}$
- $x_2$ = $\frac{9}{5}$
- $x_3$ = 0
- $x_4$ = 0
- $\bar{x}_5$ = 0
- $x_6$ = 0
- $\bar{x}_7$ = 0
- $-Z$ = -7

최적해는 7

## c

$$
\begin{aligned}
\text{Minimize} \quad & Z - \bar{x}_5 - \bar{x}_7 = 0 \\
\text{Subject to} \quad & x_1 + 4x_2 + 2x_3 - x_4 + \bar{x}_5 = 8 \\
& 3x_1 + 2x_2 - x_6 + \bar{x}_7 = 6 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 6 \\
& \bar{x}_5 ≥ 0, \bar{x}_7 ≥ 0
\end{aligned}
$$

Minimize를 Maximize로 바꿔주자.

$$
\begin{aligned}
\text{Maximize} \quad & -Z + \bar{x}_5 + \bar{x}_7 = 0 \\
\text{Subject to} \quad & x_1 + 4x_2 + 2x_3 - x_4 + \bar{x}_5 = 8 \\
& 3x_1 + 2x_2 - x_6 + \bar{x}_7 = 6 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 6 \\
& \bar{x}_5 ≥ 0, \bar{x}_7 ≥ 0
\end{aligned}
$$

표로 작성하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 \\
\bar{x}_5 & 0 & 1 & 4 & 2 & -1 & 1 & 0 & 0  & 8 \\
\bar{x}_7 & 0 & 3 & 2 & 0 & 0 & 0 & -1 & 1 & 6 \\
\hline
\end{array}
$$

basic 변수를 0이 되도록 다시 계산하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & -4 & -6 & -2 & 1 & 0 & 1 & 0 & -14 \\
\bar{x}_5 & 0 & 1 & 4 & 2 & -1 & 1 & 0 & 0  & 8 \\
\bar{x}_7 & 0 & 3 & 2 & 0 & 0 & 0 & -1 & 1 & 6 \\
\hline
\end{array}
$$

자 이제 표를 완성해보자.

- 진입변수: $x_2$
- 퇴출변수: $\bar{x}_5$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & -\frac{5}{2} & 0 & 1 & -\frac{1}{2} & \frac{3}{2} & 1 & 0 & -2 \\
x_2 & 0 & \frac{1}{4} & 1 & \frac{1}{2} & -\frac{1}{4} & \frac{1}{4} & 0 & 0  & 2 \\
\bar{x}_7 & 0 & \frac{5}{2} & 0 & -1 & \frac{1}{2} & -\frac{1}{2} & -1 & 1 & 2 \\
\hline
\end{array}
$$

- 진입변수: $x_1$
- 퇴출변수: $\bar{x}_7$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & \bar{x}_5 & x_6 & \bar{x}_7 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 \\
x_2 & 0 & 0 & 1 & \frac{3}{5} & -\frac{3}{10} & \frac{3}{10} & \frac{1}{10} & -\frac{1}{10} & \frac{9}{5} \\
x_1 & 0 & 1 & 0 & -\frac{2}{5} & \frac{1}{5} & -\frac{1}{5} & -\frac{2}{5} & \frac{2}{5} & \frac{4}{5} \\
\hline
\end{array}
$$

Phase 1 종료.

이제 필요없는 인공변수를 제거하고, 기존의 obj를 가져와서 다시 표를 만들어보자.

$$
\begin{array}{|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & x_6 &\text{RHS} \\
\hline
 & 1 & 2 & 3 & 1 & 0 & 0 & 0 \\
x_2 & 0 & 0 & 1 & \frac{3}{5} & -\frac{3}{10} & \frac{1}{10} & \frac{9}{5} \\
x_1 & 0 & 1 & 0 & -\frac{2}{5} & \frac{1}{5} & -\frac{2}{5} & \frac{4}{5} \\
\hline
\end{array}
$$

basic 변수를 0으로 만들어주자.

$$
\begin{array}{|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & x_4 & x_6 &\text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & \frac{1}{2} & \frac{1}{2} & -7 \\
x_2 & 0 & 0 & 1 & 1 & \frac{3}{5} & \frac{1}{10} & \frac{9}{5} \\
x_1 & 0 & 1 & 0 & -\frac{2}{5} & \frac{1}{5} & -\frac{2}{5} & \frac{4}{5} \\
\hline
\end{array}
$$

종료.

- $x_1$ = $\frac{4}{5}$
- $x_2$ = $\frac{9}{5}$
- $x_3$ = 0
- $x_4$ = 0
- $x_6$ = 0
- $-Z$ = -7

최적해는 7

## d

- b BFS 진행 순서

1. ($x_1$, $x_2$, $x_3$, $x_4$, $\bar{x}_5$, $x_6$, $\bar{x}_7$) = (0, 0, 0, 0, 8, 0, 6)
2. ($x_1$, $x_2$, $x_3$, $x_4$, $\bar{x}_5$, $x_6$, $\bar{x}_7$) = (0, 2, 0, 0, 0, 0, 2)
3. ($x_1$, $x_2$, $x_3$, $x_4$, $\bar{x}_5$, $x_6$, $\bar{x}_7$) = ($\frac{4}{5}$, $\frac{9}{5}$, 0, 0, 0, 0, 0)

- c BFS 진행 순서

1. ($x_1$, $x_2$, $x_3$, $x_4$, $\bar{x}_5$, $x_6$, $\bar{x}_7$) = (0, 0, 0, 0, 8, 0, 6)
2. ($x_1$, $x_2$, $x_3$, $x_4$, $\bar{x}_5$, $x_6$, $\bar{x}_7$) = (0, 2, 0, 0, 0, 0, 2)
3. ($x_1$, $x_2$, $x_3$, $x_4$, $x_6$) = ($\frac{4}{5}$, $\frac{9}{5}$, 0, 0, 0)

두 방법의 BF 해 진행 과정과 최종 해는 동일하다.

인공 변수를 사용한 인공 문제에만 가능한 해는 인공 변수 $\bar{x}_5$와 $\bar{x}_7$이 양수인 경우입니다. 초기 BF 해인 (0, 0, 0, 0, 8, 0, 6)가 여기에 해당합니다. 이 해는 인공 변수($\bar{x}_5 = 8$, $\bar{x}_7 = 6$)가 양수이므로 원래 문제에서는 가능해가 아닙니다.

최종 BFS인 ($\frac{4}{5}$, $\frac{9}{5}$, 0, 0, 0, 0, 0)는 인공 변수 $\bar{x}_5$와 $\bar{x}_7$가 모두 0이므로 실제 문제에서도 가능해다. 
이것이 바로 Phase 1과 Big-M 방법의 목적이며, 인공 변수들이 모두 0이 되는 실행 가능한 해를 찾고, 그 다음에 원래 목적함수에 대해 최적화를 진행하는 것이다.

따라서

- 인공 변수를 사용한 인공 문제에만 가능한 해 = 인공 변수가 0이 아닌 해 = (0, 0, 0, 0, 8, 0, 6), (0, 2, 0, 0, 0, 0, 2)
- 실제 문제에도 가능한 해 = 인공 변수가 0인 해 = ($\frac{4}{5}$, $\frac{9}{5}$, 0, 0, 0, 0, 0)

# 4.6-8

## a

$$
\begin{aligned}
\text{Minimize} \quad & Z - \bar{x}_4 - \bar{x}_6 = 0 \\
\text{Subject to} \quad & 5x_1 + 2x_2 + 7x_3 + \bar{x}_4 = 420 \\
& 3x_1 + 2x_2 + 5x_3 - x_5 + \bar{x}_6 = 280 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 5 \\
& \bar{x}_4 ≥ 0, \bar{x}_6 ≥ 0
\end{aligned}
$$

Minimize를 Maximize로 바꿔주자.

$$
\begin{aligned}
\text{Maximize} \quad & -Z + \bar{x}_4 + \bar{x}_6 = 0 \\
\text{Subject to} \quad & 5x_1 + 2x_2 + 7x_3 + \bar{x}_4 = 420 \\
& 3x_1 + 2x_2 + 5x_3 - x_5 + \bar{x}_6 = 280 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 5 \\
& \bar{x}_4 ≥ 0, \bar{x}_6 ≥ 0
\end{aligned}
$$

표로 작성하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & \bar{x}_4 & x_5 & \bar{x}_6 & \text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 1 & 0 & 1 & 0 \\
\bar{x}_4 & 0 & 5 & 2 & 7 & 1 & 0 & 0 & 420 \\
\bar{x}_6 & 0 & 3 & 2 & 5 & 0 & -1 & 1 & 280 \\
\hline
\end{array}
$$

basic 변수를 0이 되도록 다시 계산하면

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & \bar{x}_4 & x_5 & \bar{x}_6 & \text{RHS} \\
\hline
 & 1 & -8 & -4 & -12 & 0 & 1 & 0 & -700 \\
\bar{x}_4 & 0 & 5 & 2 & 7 & 1 & 0 & 0 & 420 \\
\bar{x}_6 & 0 & 3 & 2 & 5 & 0 & -1 & 1 & 280 \\
\hline
\end{array}
$$

자 이제 표를 완성해보자.

- 진입변수: $x_3$
- 퇴출변수: $\bar{x}_6$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & \bar{x}_4 & x_5 & \bar{x}_6 & \text{RHS} \\
\hline
 & 1 & -\frac{4}{5} & \frac{4}{5} & 0 & 0 & -\frac{7}{5} & \frac{12}{5} & -28 \\
\bar{x}_4 & 0 & \frac{4}{5} & -\frac{4}{5} & 0 & 1 & \frac{7}{5} & -\frac{7}{5} & 28 \\
x_3 & 0 & \frac{3}{5} & \frac{2}{5} & 1 & 0 & -\frac{1}{5} & \frac{1}{5} & 56 \\
\hline
\end{array}
$$

- 진입변수: $x_5$
- 퇴출변수: $\bar{x}_4$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & -Z & x_1 & x_2 & x_3 & \bar{x}_4 & x_5 & \bar{x}_6 & \text{RHS} \\
\hline
 & 1 & 0 & 0 & 0 & 1 & 0 & 1 & 0 \\
x_5 & 0 & \frac{4}{7} & -\frac{4}{7} & 0 & \frac{5}{7} & 1 & -1 & 20 \\
x_3 & 0 & \frac{5}{7} & \frac{2}{7} & 1 & \frac{1}{7} & 0 & 0 & 60 \\
\hline
\end{array}
$$

종료.

초기 BFS ($x_1, x_2, x_3, x_5$) = (0, 0, 60, 20)

# 4.7-3

## a

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

# 그래프 설정
plt.figure(figsize=(10, 7))
plt.axhline(y=0, color='k', linestyle='-', alpha=0.3)
plt.axvline(x=0, color='k', linestyle='-', alpha=0.3)

# x1, x2 범위 설정
x1 = np.linspace(0, 30, 1000)
x2 = np.linspace(0, 30, 1000)

# 제약 조건 경계선 그리기
# 3x1 ≤ 60 → x1 ≤ 20
plt.plot([20, 20], [0, 30], 'r-', label='$3x_1 = 60$')

# 2x1 + 3x2 ≤ 75
x2_constraint2 = (75 - 2*x1) / 3
valid_x1 = x1[x2_constraint2 >= 0]
valid_x2 = x2_constraint2[x2_constraint2 >= 0]
plt.plot(valid_x1, valid_x2, 'g-', label='$2x_1 + 3x_2 = 75$')

# 2x2 ≤ 40 → x2 ≤ 20
plt.plot([0, 30], [20, 20], 'b-', label='$2x_2 = 40$')

# 목적 함수 방향 벡터 (3, 2)
vector = np.array([3, 2])
plt.quiver(0, 0, 8 * vector[0], 8 * vector[1], angles='xy', scale_units='xy', scale=1, color='red')
plt.text(8*vector[0]+0.1, 8*vector[1]+1, f'c({vector[0]}, {vector[1]})', fontsize=12)

# 가능 해 영역 색칠하기
vertices = np.array([[0, 0], [20, 0], [20, 35/3], [15/2, 20], [0, 20]])
polygon = Polygon(vertices, alpha=0.3, color='skyblue')
plt.gca().add_patch(polygon)

z_values = [20, 40, 60, 75, round(250/3, 3)]  # 목적 함수 값 (적절히 선택)
for z in z_values:
    # x₂ = (z - 3x₁) / 2
    iso_x1 = np.linspace(-1, 25, 100)
    iso_x2 = (z - 3 * iso_x1) / 2  # 수직 직선의 방정식 (기울기 -3/2)
    # 등고선 그리기
    plt.plot(iso_x1, iso_x2, 'k--', alpha=0.5)
    # 목적 함수 값 표시
    # 텍스트 위치는 z 값에 따라 적절히 조정
    plt.text(z / 3 - 1, 2 + (z == 75), f'z = {z}', fontsize=9, color='navy',
             bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=1))

# 그래프 설정
plt.title('Feasible Area and Objective Vector', fontsize=14)
plt.xlabel('$x_1$', fontsize=12)
plt.ylabel('$x_2$', fontsize=12)
plt.xlim(-1, 25)
plt.ylim(-1, 25)
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()
```

최적해는 $\frac{35}{3}$

## b

- 자원 1: 60
- 자원 2: 75
- 자원 3: $\frac{70}{3}$

## c

15

# 4.7-4

표준형으로 변환하면

$$
\begin{aligned}
\text{Maximize} \quad & Z - x_1 + 7x_2 -3x_3 = 0 \\
\text{Subject to} \quad & 2x_1 + x_2 - x_3 + x_4 = 4 \\
& 4x_1 - 3x_2 + x_5 = 2 \\
& -3x_1 + 2x_2 + x_3 + x_6 = 3 \\
\text{and} \\
& x_j ≥ 0, for j = 1, 2, 3, 4, 5, 6
\end{aligned}
$$

## a

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & \text{RHS} \\
\hline
 & 1 & -1 & 7 & -3 & 0 & 0 & 0 & 0 \\
x_4 & 0 & 2 & 1 & -1 & 1 & 0 & 0 & 4 \\
x_5 & 0 & 4 & -3 & 0 & 0 & 1 & 0 & 2 \\
x_6 & 0 & -3 & 2 & 1 & 0 & 0 & 1 & 3 \\
\hline
\end{array}
$$

- 진입변수: $x_3$
- 퇴출변수: $x_6$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & \text{RHS} \\
\hline
 & 1 & -10 & 13 & 0 & 0 & 0 & 3 & 9 \\
x_4 & 0 & 2 & 1 & -1 & 1 & 0 & 0 & 7 \\
x_5 & 0 & 4 & -3 & 0 & 0 & 1 & 0 & 2 \\
x_3 & 0 & -3 & 2 & 1 & 0 & 0 & 1 & 3 \\
\hline
\end{array}
$$

- 진입변수: $x_1$
- 퇴출변수: $x_5$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & \text{RHS} \\
\hline
 & 1 & 0 & \frac{11}{2} & 0 & 0 & \frac{5}{2} & 3 & 14 \\
x_4 & 0 & 0 & \frac{9}{4} & 0 & 1 & \frac{1}{4} & 1 & \frac{15}{2} \\
x_1 & 0 & 1 & -\frac{3}{4} & 0 & 0 & \frac{1}{4} & 0 & \frac{1}{2} \\
x_3 & 0 & 0 & -\frac{1}{4} & 1 & 0 & \frac{3}{4} & 1 & \frac{9}{2} \\
\hline
\end{array}
$$

종료.

- $x_1$ = $\frac{1}{2}$
- $x_2$ = 0
- $x_3$ = $\frac{9}{2}$
- $x_4$ = $\frac{15}{2}$
- $x_5$ = 0
- $x_6$ = 0
- $Z$ = 14

## b

- 자원 1 = $-\frac{7}{2}$
- 자원 2 = 2
- 자원 3 = 3

# 5.1-6

## a

1. $-3x₁ + 2x₂ = 30, 2x₁ + x₂ = 50$
  - 꼭짓점: (10, 30)
  - 가능해

2. $-3x₁ + 2x₂ = 30, x₁ + x₂ = 30$
  - 꼭짓점: (6, 24)
  - $2x_1 + x_2 ≥ 50$ 제약 불만족

3. $-3x₁ + 2x₂ = 30, x₁ = 0$
  - 꼭짓점: (0, 15)
  - $2x_1 + x_2 ≥ 50$ 제약 불만족

4. $-3x₁ + 2x₂ = 30, x₂ = 0$
  - 꼭짓점: (-10, 0)
  - $x_1 ≥ 0$ 제약 불만족

5. $2x₁ + x₂ = 50, x₁ + x₂ = 30$
  - 꼭짓점: (20, 10)
  - 가능해

6. $2x₁ + x₂ = 50, x₁ = 0$
  - 꼭짓점: (0, 50)
  - $-3x_1 + 2x_2 ≤ 30$ 제약 불만족

7. $2x₁ + x₂ = 50, x₂ = 0$
  - 꼭짓점: (25, 0)
  - $-3x_1 + 2x_2 ≤ 30$ 제약 불만족

8. $x₁ + x₂ = 30, x₁ = 0$
  - 꼭짓점: (0, 30)
  - $-3x_1 + 2x_2 ≤ 30$ 제약 불만족

9. $x₁ + x₂ = 30, x₂ = 0$
  - 꼭짓점: (30, 0)
  - 가능해

10. $x₁ = 0, x₂ = 0$
  - 꼭짓점: (0, 0)
  - $2x_1 + x_2 ≥ 50$ 제약 불만족

## b

1. (10, 30, 0, 0, 10)

2. (20, 10, 80, 0, 0)

3. (30, 0, 60, 10, 0)

# 5.1-20

## a

(2, 4, 3, 2, 0, 0, 0)에서 비기저변수는 ($x_5, x_6, x_7$)이고, 기저변수는 ($x_1, x_2, x_3, x_4$)이다.

α만큼 움직일 때, 비기저변수의 변화량은 (2, 0, 0)로, $x_5$만 증가한다. 고로 진입기저에 포함됨을 알 수 있다.

## b

- $x_1$ = 2 + 2α ≥ 0 (항상 양수)
- $x_2$ = 4 - 2α ≥ 0 → 4 - 2α = 0 → α = 2
- $x_3$ = 3 + α ≥ 0 (항상 양수)
- $x_4$ = 2 - 2α ≥ 0 → 2 - 2α = 0 → α = 1

하지만 α는 0 ≤ α ≤ 1로 제한된다. 따라서 α = 1일 때

- $x_1$ = 4
- $x_1$ = 2
- $x_1$ = 4
- $x_1$ = 0

$x_4$가 0으로 떨어지므로, 탈락 기저 변수는 $x_4$

## c

α가 1일 때 새로운 BFS는 (4, 2, 4, 0, 2, 0, 0)이다.

# 5.2-1

## a

최적해는 $C_BB^{-1}b$

$$
C_B = [6, 8, 9], \\
B^{-1} = \frac{1}{27}\begin{bmatrix}
11 & -3 & 1 \\
-6 & 9 & -3 \\
2 & -3 & 10
\end{bmatrix}, \\
b = \begin{bmatrix}
180 \\
270 \\
180
\end{bmatrix}
$$

답은 990

## b

$$
B^{-1}b = \begin{bmatrix}
50 \\
30 \\
50
\end{bmatrix}
$$

최적해에서 BFS는 (30, 0, 50, 0, 50)

이때 세 자원의 잠재 가격은

- resource 1: 180
- resource 2: 270
- resource 3: 180

# 5.2-2

## iteration 1

- basic: $x_6, x_7$

Reduced cost: $C_bB{-1}N - C_n$,  
$C_b = [0, 0]$ → Rc = $-C_n$ = [-5, -8, -7, -4, -6]

- enter: $x_2$

$$
B^{-1} = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}, \\
A_*2 = \begin{bmatrix}
3 \\
5
\end{bmatrix}, \\
b = \begin{bmatrix}
20 \\
30
\end{bmatrix}
$$

min ratio test: $[\frac{20}{3}, 6]$

- exit: $x_7$

## iteration 2

- basic: $x_6, x_2$

$$
C_b = [0, 8], \\
B = \begin{bmatrix}
1 & 3 \\
0 & 5
\end{bmatrix}, \\
B^{-1} = \begin{bmatrix}
1 & -\frac{3}{5} \\
0 & \frac{1}{5}
\end{bmatrix}
$$

$$
N = \begin{bmatrix}
2 & 3 & 2 & 2 & 0 \\
3 & 4 & 2 & 4 & 1
\end{bmatrix}, \\
C_n = \begin{bmatrix}
5 & 7 & 4 & 6 & 0
\end{bmatrix}
$$

- Reduced cost:

$$
\begin{bmatrix}
0 & 8\end{bmatrix} \begin{bmatrix}
1 & -\frac{3}{5} \\
0 & \frac{1}{5}
\end{bmatrix} \begin{bmatrix}
2 & 3 & 2 & 2 & 0 \\
3 & 4 & 2 & 4 & 1
\end{bmatrix} - \begin{bmatrix}
5 & 7 & 4 & 6 & 0
\end{bmatrix} = \begin{bmatrix}
-\frac{1}{5} & -\frac{3}{5} & -\frac{4}{5} & \frac{2}{5} & \frac{8}{5}
\end{bmatrix}
$$

- enter: $x_4$

$$
A_*4B^{-1} = \begin{bmatrix}
2 \\
2
\end{bmatrix} \begin{bmatrix}
1 & -\frac{3}{5} \\
0 & \frac{1}{5}
\end{bmatrix} = \begin{bmatrix}
\frac{4}{5} \\
\frac{2}{5}
\end{bmatrix}, \\
bB^{-1} = \begin{bmatrix}
2 \\
6
\end{bmatrix}
$$

min ratio test: $[\frac{5}{2}, 15]$

- exit: $x_6$

## iteration 3

- basic: $x_4, x_2$

$$
C_b = [4, 8], \\
B = \begin{bmatrix}
2 & 3 \\
2 & 5
\end{bmatrix}, \\
B^{-1} = \begin{bmatrix}
\frac{5}{4} & -\frac{3}{4} \\
-\frac{1}{2} & \frac{1}{2}
\end{bmatrix}
$$

$$
N = \begin{bmatrix}
2 & 3 & 2 & 1 & 0 \\
3 & 4 & 4 & 0 & 1
\end{bmatrix}, \\
C_n = \begin{bmatrix}
5 & 7 & 6 & 0 & 0
\end{bmatrix}
$$

- Reduced cost:

$$
\begin{bmatrix}
4 & 8\end{bmatrix} \begin{bmatrix}
\frac{5}{4} & -\frac{3}{4} \\
-\frac{1}{2} & \frac{1}{2}
\end{bmatrix} \begin{bmatrix}
2 & 3 & 2 & 1 & 0 \\
3 & 4 & 4 & 0 & 1
\end{bmatrix} - \begin{bmatrix}
5 & 7 & 6 & 0 & 0
\end{bmatrix} = \begin{bmatrix}
0 & 0 & 0 & 1 & 1
\end{bmatrix}
$$

종료.

$$
bB^{-1} = \begin{bmatrix}
\frac{5}{2} \\
5
\end{bmatrix}
C_bB^{-1}b = 50
$$

- $x_1$ = 0
- $x_2$ = 5
- $x_3$ = 0
- $x_4$ = $\frac{5}{2}$
- $x_5$ = 0
- $x_6$ = 0
- $x_7$ = 0
- $Z$ = 50

