
5점 4개 10점 2개

# 반사실 주의

1. 관습과 형식 거부
2. 현실 반영 x
3. 인과관계 분명 x
4. 인물의 동기가 분명 x

## 표현주의

1. 사실적으로 표현을 안함(과장되있거나 외곡되어있음)
2. 사실적으로 연기도 안함
3. 사실적으로 상황 안보여줌
4. 상징주의와 다르게 우리 현실을 다루지만, 똑같이 재연하지 않음
5. 부조리극이 표현주의에 영향을 받아서 과장되어 있음
6. 현실적이지 않은 표현의 의도가 중요함(내면적 리얼리티)
7. 미술의 영역에서 등장(피카소)
8. 현실 거부, 저항하며 그 이면의 본질을 드러내려는 시도
9. 허위와 위선으로 가득 찬 가족제도, 관료제도, 사회질서와 산업 사회 비판. 새로운 인간 출현이 주제
10. 전보체 대사(짧은 문장), 인물의 익명성 강조, 유형화된 성격

### 게오르그 카이저 아침부터 자정까지

1. 은행원: 아무런 가치 없이 기계적으로 같은 일을 반복하는 인물
2. 그의 안경알이 그녀의 손목을 타고 기어오른다
3. 수염의 숲이 출렁거린다. 안경이 크게 뜬 두 눈의 동공 속으로 가라앉는다A
4. 정거장식 드라마. 이전 장소로 돌아가지 않고, 인물도 다시 안나옴
5. 삽화식 구성(장 들이 유기적으로 연결이 안됨)

## 부조리극

1. 비논리적인 사고, 비 논리적인 태도
2. 실존주의와 초현실주의 사상에 영향을 받음
3. 부조리한 상황과 목적이 결여되어 있는 것
4. 절박한 행위와 모순, 무의미한 언어 발화
5. 세계와 단절된 고독한 인간이 자기존재의 근원적 상황과 끊임없이 대결
6. 전통적인 연극(사실주의)의 합리성 거부. 인과성이 없다
7. 갈등을 구축하고 행동을 수행하는 인물이 없음
8. 극이 시작한 것처럼 정확하게 되돌아가 끝을 맺는 구조: 변화의 불가능

### 이오네스코 연극 - 대머리 여가수 (대머리도 여가수도 안나옴)

1. 현대의 기계문명, 부르주아 문명, 가치관의 상실 생활의 타락 항의
2. 형이상학적 차원을 상실한 세계 공격
3. 개인의 고독과 소외
4. 비열한 외부 압력과 사회의 기계적인 권력구조에 대한 복정, 개인의 신원의 불확실성

영국식: 주어진 대로 자동적으로 살아가는 개인

이상한 시계: 시간을 인식하지 못할 정도로 비 주체적으로 살아가는 인물

모든 사람 이름이 바비 와트슨: 신원의 불확실성

### 징주네와 베케트 연극 - 하녀들

1. 인간의 조건, 소외, 고독
2. 동기와 개념의 포기, 심리적 상황과 인간의 상황적 조건에 집중
3. 교훈적 목적 거부
4. 거울의 게임(연극 속의 연극): 모든 사물이 거울을 통해 드러남. 꿈이나 연극을 통해서만 원하는걸 보여주다가 붕괴됨
5. 뛰어난 언어의 아름다움

끌레르가 마담, 쏠랑주가 끌레르 역할의 연극으로 시작

마담 역할의 끌레르가 끌레르를 욕함 -> 자기 증오

끌레르 역할의 쏠랑주가 마담을 죽임 -> 자기 살해, 마담으로써 죽음, 현실에서는 하녀를 벗어날 수 없음

### 사뮤엘 베케트

부조리한 조건이 실존한다는 사실 자체에 직면하도록 문제 제기

길: 우리의 삶

나무: 존재의 표상(인간의 존재를 떠올리게 함)

모자: 이상

신발: 현실

저녁: 소멸의 시간

아침: 생명, 젊음

신발을 계속 벗는 동작을 반복: 변화의 욕망이 없음

형이상학적인 블라디미르, 현실적인 에스트라곤

고독한 존재의 살아가는 방식을 보여줌


상징주의 x, 서사극 x, 표현주의 o(게오로그 카이저 작품)
반사실주의 희곡 텍스트에 기반해서 작품하고 특징하고 기반해서
부조리극 작품하고 특징하고 기반해서
반사실주의의 사실주의와 대비되는 장르적인 특징

상징주의 x, 서사극 x, 표현주의 o(게오로그 카이저 작품)
반사실주의 희곡 텍스트에 기반해서 작품하고 특징하고 기반해서
부조리극 작품하고 특징하고 기반해서
반사실주의의 사실주의와 대비되는 장르적인 특징

# 미국 아방가르드

1. 급진적인 형식의 실험으로 관객의 인식을 바꿔주는 시도(미적인 충격)
2. 외부세계나 현실세계를 재현하지 않고, 대사 중심이 아님. 창조적인 과정을 지향
3. 급진적, 실험적, 비상업적
4. 이미지(음악, 영화, 무용. not 대사) 연극 중심
5. 하이테크놀로지나 미디어를 활용한 것은 아방가르드가 아님
6. 아방가르드 중기에는 환경연극(60년대)과 이미지 연극(70년대)이 주를 이룸. 우스터그룹(80년대)는 둘이 섞여있음

## 환경 연극

1. 관객을 공연 환경의 주요한 요소로 간주
2. 관객과 배우 사이에 존재하는 공간적 경계선을 무너뜨림
3. performance group 극단을 중심으로. 정치적이고 사회 비판적인 내용이 주조를 이룸

## 이미지 연극

이전 연극과의 차이
우스터 그룹, 미국 아방가르드 전반적으로

# 뮤지컬

## 지킬앤하이드
