---
title: OR 과제 - 6
subtitle: 20192208 김형훈
categories: ["보고서", "OR"]
date: last-modified
format: 
  pdf:
    fig-pos: 'H'
    fig-width: 6
    fig-height: 4
    documentclass: report
    papersize: a4
    top-level-division: chapter
    fontsize: 17pt
    toc: false
    geometry:
      - top=20mm
    indent-size: 2
include-in-header: 
  text: |
    \date{}
    \usepackage{fontspec}
    \setmainfont{Noto Sans KR}
    \usepackage{titlesec}
    \titleformat{\chapter}{\normalfont\huge\bfseries}{\thechapter.}{0.8em}{\huge}
    \titleformat{\subsection}[block]{\normalfont\large\bfseries}{}{0pt}{}
    \titleformat{\subsubsection}[block]{\normalfont\normalsize\bfseries}{}{0pt}{}
    \titlespacing*{\chapter}{0pt}{-20pt}{5pt}
    \titlespacing*{\section}{0pt}{10pt}{10pt}
    \newcommand{\chapterbreak}{\clearpage}
    \usepackage{setspace}
    \setstretch{1.5}
    \usepackage{tabularx}
    \newcolumntype{Y}{>{\centering\arraybackslash}X}
    \usepackage[bottom]{footmisc}
    \usepackage{setspace}
    \renewcommand{\footnotesize}{\setstretch{1.2}\fontsize{9pt}{11pt}\selectfont}
    \setlength{\skip\footins}{10pt}
    \setlength{\footnotesep}{8pt}
    \renewcommand{\footnoterule}{\vspace{1em}\hrule width 0.5\linewidth\vspace{1em}}
    \makeatletter
    \renewcommand{\@makefntext}[1]{\noindent\makebox[1.5em][r]{\@makefnmark}\hspace{0.5em}#1}
    \makeatother
    \usepackage{float}
    \usepackage{multirow}
    \usepackage{booktabs}

execute:
  echo: false
  warning: false
  message: false

---

# 6.7-2

최종 해법은 다음과 같다.

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & \text{RHS} \\
\hline
 & 1 & 0 & 0 & 2 & 5 & 0 & 100 \\
x_2 & 0 & -1 & 1 & 3 & 1 & 0 & 20 \\
x_5 & 0 & 16 & 0 & -2 & -4 & 1 & 10 \\
\hline
\end{array}
$$

## a

- $B^{-1}b_{new} = \begin{bmatrix} 
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
30 \\
90
\end{bmatrix} = \begin{bmatrix}
30 \\
-30
\end{bmatrix}$

- $Z_{new} = [5, 0] \begin{bmatrix}
30 \\
-30
\end{bmatrix} = 150$.

(0) $Z + 2x_3 + 5x_4 = 150$
(1) $-x_1 + x_2 + 3x_3 + x_4 = 30$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 = -30$

- 기저해: (0, 30, 0, 0, -30)
- $x_5 < 0$ (infeasible)
- Z-행의 비기저 변수 $x_1, x_3, x_4$의 계수는 각각 $0, 2, 5$. bfs였다면 최적 조건을 만족

## b

- $B^{-1}b_{new} = \begin{bmatrix} 
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
20 \\
70
\end{bmatrix} = \begin{bmatrix}
20 \\
-10
\end{bmatrix}$

- $Z_{new} = [5, 0] \begin{bmatrix}
20 \\
-10
\end{bmatrix} = 100$.

(0) $Z + 2x_3 + 5x_4 = 100$
(1) $-x_1 + x_2 + 3x_3 + x_4 = 20$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 = -10$

- 기저해: (0, 20, 0, 0, -10). infeasible
- rc: (0, 0, 2, 5, 0). bfs였다면 최적

## c

- $B^{-1}b_{new} = \begin{bmatrix} 
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
10 \\
100
\end{bmatrix} = \begin{bmatrix}
10 \\
60
\end{bmatrix}$

- $Z_{new} = [5, 0] \begin{bmatrix}
10 \\
60
\end{bmatrix} = 50$.

(0) $Z + 2x_3 + 5x_4 = 50$
(1) $-x_1 + x_2 + 3x_3 + x_4 = 10$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 = 60$

- 기저해: (0, 10, 0, 0, 60). feasible
- rc: 0, 0, 2, 5, 0. 최적

## d

- origin: $z - c_3 = 2, z = 15$
- new: $z - c_3 = 15 - 80 = -65$

(0) $Z - 65x_3 + 5x_4 = 100$
(1) $-x_1 + x_2 + 3x_3 + x_4 = 20$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 = 10$

- 기저해: (0, 20, 0, 0, 10). feasible
- rc: (0, 0, 7, 5, 0). 최적

## e

- $x_1$의 rc: $c_BB^{-1}A_{⋅1} - c_1 = [5, 0] \begin{bmatrix}
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
0 \\
5
\end{bmatrix} - (-2) = 2$
- $N_{⋅1}$: $B^{-1}A_{⋅1} = \begin{bmatrix}
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
0 \\
5
\end{bmatrix} = \begin{bmatrix}
0 \\
5
\end{bmatrix}$

(0) $Z + 2x_1 + 2x_3 + 5x_4 = 100$
(1) $x_2 + 3x_3 + x_4 = 20$
(2) $5x_1 - 2x_3 - 4x_4 + x_5 = 10$

- 기저해: (0, 20, 0, 0, 10). feasible
- rc: (2, 0, 7, 5, 0). 최적

## f

- $B = \begin{bmatrix}
2 & 0 \\
5 & 1
\end{bmatrix}$
- $B^{-1} = \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix}$
- $c_B = [6, 0]$
- $B^{-1}b = \begin{bmatrix} 
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
20 \\
90
\end{bmatrix} = \begin{bmatrix}
10 \\
40
\end{bmatrix}$
- $Z = [6, 0] \begin{bmatrix}
10 \\
40
\end{bmatrix} = 60$.
- $x_1$의 rc: $c_BB^{-1}A_{⋅1} - c_1 = [6, 0] \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
-1 \\
12
\end{bmatrix} - (-5) = 2$
- $N_{⋅1}$: $B^{-1}A_{⋅1} = \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
-1 \\
12
\end{bmatrix} = \begin{bmatrix}
-\frac{1}{2} \\
\frac{29}{2}
\end{bmatrix}$

- $x_3$의 rc: $c_BB^{-1}A_{⋅3} - c_3 = [6, 0] \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
3 \\
10
\end{bmatrix} - 13 = -4$
- $N_{⋅3}$: $B^{-1}A_{⋅3} = \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
3 \\
10
\end{bmatrix} = \begin{bmatrix}
\frac{3}{2} \\
\frac{5}{2}
\end{bmatrix}$

- $x_4$의 rc: $c_BB^{-1}A_{⋅4} - c_4 = [6, 0] \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
1 \\
0
\end{bmatrix} - 0 = 3$
- $N_{⋅4}$: $B^{-1}A_{⋅4} = \begin{bmatrix}
\frac{1}{2} & 0 \\
-\frac{5}{2} & 1
\end{bmatrix} \begin{bmatrix}
1 \\
0
\end{bmatrix} = \begin{bmatrix}
\frac{1}{2} \\
-\frac{5}{2}
\end{bmatrix}$

(0) $Z + 2x_1 - 4x_3 + 3x_4 = 60$
(1) $-\frac{1}{2}x_1 + x_2 + \frac{3}{2}x_3 + \frac{1}{2}x_4 = 10$
(2) $\frac{29}{2}x_1 + \frac{5}{2}x_3 - \frac{5}{2}x_4 + x_5 = 40$

- 기저해: (0, 10, 0, 0, 40). feasible
- rc: (2, 0, -4, 3, 0). 최적 아님.

## g

- $N_{⋅6}$: $B^{-1}A_{⋅6} = \begin{bmatrix}
1 & 0 \\
-4 & 1
\end{bmatrix} \begin{bmatrix}
3 \\
5
\end{bmatrix} = \begin{bmatrix}
3 \\
-7
\end{bmatrix}$

- $x_6$의 rc:  $(5,0) \begin{bmatrix}
3 \\
-7
\end{bmatrix} - 10 = 5$.

(0) $Z + 2x_3 + 5x_4 + 5x_6 = 100$
(1) $-x_1 + x_2 + 3x_3 + x_4 + 3x_6 = 20$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 - 7x_6 = 10$

- 기저해: (0, 20, 0, 0, 10, 0). feasible
- rc: (0, 0, 2, 5, 0, 5). 최적.

## h

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & \text{RHS} \\
\hline
 & 1 & 0 & 0 & 2 & 5 & 0 & 0 & 100 \\
x_2 & 0 & -1 & 1 & 3 & 1 & 0 & 0 & 20 \\
x_5 & 0 & 16 & 0 & -2 & -4 & 1 & 0 & 10 \\
x_6 & 0 & 2 & 3 & 5 & 0 & 0 & 1 & 50 \\
\hline
\end{array}
$$

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & \text{RHS} \\
\hline
 & 1 & 0 & 0 & 2 & 5 & 0 & 0 & 100 \\
x_2 & 0 & -1 & 1 & 3 & 1 & 0 & 0 & 20 \\
x_5 & 0 & 16 & 0 & -2 & -4 & 1 & 0 & 10 \\
x_6 & 0 & 5 & 0 & -4 & -3 & 0 & 1 & -10 \\
\hline
\end{array}
$$

(0) $Z + 2x_3 + 5x_4 = 100$
(1) $-x_1 + x_2 + 3x_3 + x_4 = 20$
(2) $16x_1 - 2x_3 - 4x_4 + x_5 = 10$
(3) $5x_1 - 4x_3 - 3x_4 + x_6 = -10$

- 기저해: (0, 20, 0, 0, 10, -10). infeasible
- rc: (0, 0, 2, 5, 0). bfs면 최적.

## i

- $B = \begin{bmatrix}
1 & 0 \\
5 & 1
\end{bmatrix}$
- $B^{-1} = \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix}$
- $c_B = [5, 0]$
- $B^{-1}b = \begin{bmatrix} 
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
20 \\
100
\end{bmatrix} = \begin{bmatrix}
20 \\
0
\end{bmatrix}$
- $Z = [5, 0] \begin{bmatrix}
20 \\
0
\end{bmatrix} = 100$

- $x_1$의 rc: $c_BB^{-1}A_{⋅1} - c_1 = [5, 0] \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
-1 \\
10
\end{bmatrix} - (-5) = 0$
- $N_{⋅1}$: $B^{-1}A_{⋅1} = \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
-1 \\
10
\end{bmatrix} = \begin{bmatrix}
-1  \\
15
\end{bmatrix}$

- $x_3$의 rc: $c_BB^{-1}A_{⋅3} - c_3 = [6, 0] \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
3 \\
10
\end{bmatrix} - 13 = 2$
- $N_{⋅3}$: $B^{-1}A_{⋅3} = \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
3 \\
10
\end{bmatrix} = \begin{bmatrix}
3 \\
-5
\end{bmatrix}$

- $x_4$의 rc: $c_BB^{-1}A_{⋅4} - c_4 = [6, 0] \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
1 \\
0
\end{bmatrix} - 0 = 5$

- $N_{⋅4}$: $B^{-1}A_{⋅4} = \begin{bmatrix}
1 & 0 \\
-5 & 1
\end{bmatrix} \begin{bmatrix}
1 \\
0
\end{bmatrix} = \begin{bmatrix}
1 \\
-5
\end{bmatrix}$

(0) $Z + 0x_1 + 2x_3 + 5x_4 = 100$
(1) $x_2 - x_1 + 3x_3 + x_4 = 20$
(2) $x_5 + 15x_1 - 5x_3 - 5x_4 = 0$

- 기저해: (0, 20, 0, 0, 0). feasible
- rc: (0, 0, 2, 5, 0). 최적.

# 7.1-4

## a

### 쌍대문제

$$
\begin{aligned}
\text{Minimize} \quad & W = 40y_1 + 20y_2 + 90y_3 \\
\text{Subject to} \quad & 3y_1 + y_2 + 5y_3 ≥ 5 \\
& y_1 + y_2 + 3y_3 ≥ 10 \\
& y_1, y_2, y_3 ≥ 0
\end{aligned}
$$

### iteration 1

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & \text{RHS} \\
\hline
 & 1 & -5 & -10 & 0 & 0 & 0 & 0 \\
x_3 & 0 & 3 & 1 & 1 & 0 & 0 & 40 \\
x_4 & 0 & 1 & 1 & 0 & 1 & 0 & 20 \\
x_5 & 0 & 5 & 3 & 0 & 0 & 1 & 90 \\
\hline
\end{array}
$$

- bfs: (0, 0, 40, 20, 90)
- 상보기저해: (0, 0, 0, -5, -10)

### iteration 2

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & Z & x_1 & x_2 & x_3 & x_4 & x_5 & \text{RHS} \\
\hline
 & 1 & 5 & 0 & 0 & 10 & 0 & 200 \\
x_3 & 0 & 2 & 0 & 1 & -1 & 0 & 20 \\
x_2 & 0 & 1 & 1 & 0 & 1 & 0 & 20 \\
x_5 & 0 & 2 & 0 & 0 & -3 & 1 & 30 \\
\hline
\end{array}
$$

- bfs: (0, 20, 20, 0, 30)
- 상보기저해: (0, 10, 0, 5, 0)

## b

$$
\begin{aligned}
\text{Minimize} \quad & W = 40y_1 + 20y_2 + 90y_3 \\
\text{Subject to} \quad & -3y_1 - y_2 - 5y_3 ≤ -5 \\
& -y_1 - y_2 - 3y_3 ≤ -10 \\
& y_1, y_2, y_3 ≥ 0
\end{aligned}
$$

$$
\begin{aligned}
\text{Maximize} \quad & -W = -40y_1 - 20y_2 - 90y_3 \\
\text{Subject to} \quad & -3y_1 - y_2 - 5y_3 + y_4 = -5 \\
& -y_1 - y_2 - 3y_3 + y_5 = -10 \\
& y_1, y_2, y_3, y_4, y_5 ≥ 0
\end{aligned}
$$

### iteration 1

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -W & y_1 & y_2 & y_3 & y_4 & y_5 & \text{RHS} \\
\hline
 & 1 & 40 & 20 & 90 & 0 & 0 & 0 \\
y_4 & 0 & -3 & -1 & -5 & 1 & 0 & -5 \\
y_5 & 0 & -1 & -1 & -3 & 0 & 1 & -10 \\
\hline
\end{array}
$$

- bfs: (0, 0, 0, -5, -10)

### iteration 2

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
 & -W & y_1 & y_2 & y_3 & y_4 & y_5 & \text{RHS} \\
\hline
 & 1 & 20 & 0 & 30 & 0 & 20 & -200 \\
y_4 & 0 & -2 & 0 & -2 & 1 & -1 & 5 \\
y_2 & 0 & 1 & 1 & 3 & 0 & -1 & 10 \\
\hline
\end{array}
$$

- bfs: (0, 10, 0, 5, 0)

# 7.3-1

$$
\begin{aligned}
\text{Maximize} \quad & Z = 2x_1 + 3x_2 \\
\text{Subject to} \quad & 3x_1 - 9x_2 ≤ 20 \\
& 0 ≤ x_1 ≤ \frac{40}{3}, 0 ≤ x_2 ≤ \frac{40}{9}
\end{aligned}
$$

## a

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

plt.figure(figsize=(8, 8))  # 정사각형 비율로 변경
plt.axhline(y=0, color='k', linestyle='-', alpha=0.3)
plt.axvline(x=0, color='k', linestyle='-', alpha=0.3)

# x1, x2 범위 설정
x1 = np.linspace(0, 15, 1000)
x2 = np.linspace(0, 15, 1000)

# 제약 조건 경계선 그리기
# 3x₁ - 9x₂ ≤ 20
x2_constraint1 = (3 * x1 - 20) / 9
valid_x1 = x1[x1 >= 0]  # x1이 양수일 때
valid_x2 = x2_constraint1[x1 >= 0]
valid_indices = valid_x2 >= 0
plt.plot(valid_x1, valid_x2, 'r-', label='$3x_1 - 9x_2 = 20$')

# 3x₁ ≤ 40
plt.plot([40/3, 40/3], [0, 42], 'g-', label='$3x_1 = 40$')

# 9x₂ ≤ 40
plt.plot([0, 42], [40/9, 40/9], 'b-', label='$9x_2 = 40$')

# 목적 함수 방향 벡터 (2, 3)
vector = np.array([2, 3])
normalized_vector = vector / np.linalg.norm(vector) * 5  # 벡터 크기 조정
plt.quiver(0, 0, normalized_vector[0], normalized_vector[1], 
           angles='xy', scale_units='xy', scale=1, color='red')
plt.text(normalized_vector[0]+0.1, normalized_vector[1]+0.2, 
         f'c({vector[0]}, {vector[1]})', fontsize=12)

# 가능 해 영역 색칠하기
# 교점 계산
x1_max = 40/3
x2_intersect1 = (3 * x1_max - 20) / 9

vertices = np.array([
    [0, 0],
    [20/3, 0],
    [x1_max, x2_intersect1],
    [x1_max, 40/9],
    [0, 40/9]
])
polygon = Polygon(vertices, alpha=0.3, color='skyblue')
plt.gca().add_patch(polygon)

plt.xlabel('$x_1$', fontsize=12)
plt.ylabel('$x_2$', fontsize=12)
plt.xlim(0, 15)
plt.ylim(0, 5)  # y축 범위 조정
plt.legend(loc='upper right')
plt.tight_layout(pad=1.1)
```

- bfs: $(\frac{40}{3}, \frac{40}{9})$
- obj: 40

## b

$$
\begin{aligned}
\text{Maximize} \quad & Z - 2x_1 - 3x_2 = 0 \\
\text{Subject to} \quad & x_3 = 20 - 3x_1 + 9x_2 \\
& 0 ≤ x_1 ≤ \frac{40}{3}, 0 ≤ x_2 ≤ \frac{40}{9}, x_3 ≥ 0
\end{aligned}
$$

- $x_2$ enter

$$
\begin{aligned}
Z - 2x_1 - 3x_2 = 0\\
x_3 = 20 + 9x_2 \quad ... \quad x_2 ≤ \frac{40}{9}
\end{aligned}
$$

$$
\begin{aligned}
x_2 = \frac{40}{9} - y_2 \\
x_3 = 60 - 3x_1 - 9y_2 \quad ... \quad x_1 ≤ \frac{40}{3} \\
Z - 2x_1 + 3y_2 = \frac{40}{3}\\
\end{aligned}
$$

- $x_1$ enter

$$
\begin{aligned}
x_1 = \frac{40}{3} - y_1 \\
x_3 = 20 + 3y_1 - 9y_2 \\
Z + 2y_1 + 3y_2 = 40 \\
\end{aligned}
$$

- bfs$(x_1, x_2, x_3, y_1, y_2)$: $(\frac{40}{3}, \frac{40}{9}, 20, 0, 0)$
- obj: = 40

## c

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

plt.figure(figsize=(8, 8))  # 정사각형 비율로 변경
plt.axhline(y=0, color='k', linestyle='-', alpha=0.3)
plt.axvline(x=0, color='k', linestyle='-', alpha=0.3)

# x1, x2 범위 설정
x1 = np.linspace(0, 15, 1000)
x2 = np.linspace(0, 15, 1000)

# 제약 조건 경계선 그리기
# 3x₁ - 9x₂ ≤ 20
x2_constraint1 = (3 * x1 - 20) / 9
valid_x1 = x1[x1 >= 0]  # x1이 양수일 때
valid_x2 = x2_constraint1[x1 >= 0]
valid_indices = valid_x2 >= 0
plt.plot(valid_x1, valid_x2, 'r-', label='$3x_1 - 9x_2 = 20$')

# 3x₁ ≤ 40
plt.plot([40/3, 40/3], [0, 42], 'g-', label='$3x_1 = 40$')

# 9x₂ ≤ 40
plt.plot([0, 42], [40/9, 40/9], 'b-', label='$9x_2 = 40$')

# 가능 해 영역 색칠하기
# 교점 계산
x1_max = 40/3
x2_intersect1 = (3 * x1_max - 20) / 9

vertices = np.array([
    [0, 0],
    [20/3, 0],
    [x1_max, x2_intersect1],
    [x1_max, 40/9],
    [0, 40/9]
])
polygon = Polygon(vertices, alpha=0.3, color='skyblue')
plt.gca().add_patch(polygon)

plt.scatter(0, 0, color='black', s=80, zorder=5)
plt.annotate('(0, 0)', 
             (0, 0), 
             xytext=(10, 10), 
             textcoords='offset points',
             fontsize=12)

plt.xlabel('$x_1$', fontsize=12)
plt.ylabel('$x_2$', fontsize=12)
plt.xlim(0, 15)
plt.ylim(0, 5)  # y축 범위 조정
plt.legend(loc='upper right')
plt.tight_layout(pad=1.1)
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

plt.figure(figsize=(8, 8))  # 정사각형 비율로 변경
plt.axhline(y=0, color='k', linestyle='-', alpha=0.3)
plt.axvline(x=0, color='k', linestyle='-', alpha=0.3)

# x1, x2 범위 설정
x1 = np.linspace(0, 15, 1000)
x2 = np.linspace(0, 15, 1000)

# 제약 조건 경계선 그리기
# 3x₁ - 9x₂ ≤ 20
x2_constraint1 = (3 * x1 - 20) / 9
valid_x1 = x1[x1 >= 0]  # x1이 양수일 때
valid_x2 = x2_constraint1[x1 >= 0]
valid_indices = valid_x2 >= 0
plt.plot(valid_x1, valid_x2, 'r-', label='$3x_1 - 9x_2 = 20$')

# 3x₁ ≤ 40
plt.plot([40/3, 40/3], [0, 42], 'g-', label='$3x_1 = 40$')

# 9x₂ ≤ 40
plt.plot([0, 42], [40/9, 40/9], 'b-', label='$9x_2 = 40$')

# 가능 해 영역 색칠하기
# 교점 계산
x1_max = 40/3
x2_intersect1 = (3 * x1_max - 20) / 9

vertices = np.array([
    [0, 0],
    [20/3, 0],
    [x1_max, x2_intersect1],
    [x1_max, 40/9],
    [0, 40/9]
])
polygon = Polygon(vertices, alpha=0.3, color='skyblue')
plt.gca().add_patch(polygon)

plt.scatter(0, 40/9, color='black', s=80, zorder=5)
plt.annotate('(0, 40/9)', 
             (0, 40/9), 
             xytext=(10, 10), 
             textcoords='offset points',
             fontsize=12)

plt.xlabel('$x_1$', fontsize=12)
plt.ylabel('$x_2$', fontsize=12)
plt.xlim(0, 15)
plt.ylim(0, 5)  # y축 범위 조정
plt.legend(loc='upper right')
plt.tight_layout(pad=1.1)
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

plt.figure(figsize=(8, 8))  # 정사각형 비율로 변경
plt.axhline(y=0, color='k', linestyle='-', alpha=0.3)
plt.axvline(x=0, color='k', linestyle='-', alpha=0.3)

# x1, x2 범위 설정
x1 = np.linspace(0, 15, 1000)
x2 = np.linspace(0, 15, 1000)

# 제약 조건 경계선 그리기
# 3x₁ - 9x₂ ≤ 20
x2_constraint1 = (3 * x1 - 20) / 9
valid_x1 = x1[x1 >= 0]  # x1이 양수일 때
valid_x2 = x2_constraint1[x1 >= 0]
valid_indices = valid_x2 >= 0
plt.plot(valid_x1, valid_x2, 'r-', label='$3x_1 - 9x_2 = 20$')

# 3x₁ ≤ 40
plt.plot([40/3, 40/3], [0, 42], 'g-', label='$3x_1 = 40$')

# 9x₂ ≤ 40
plt.plot([0, 42], [40/9, 40/9], 'b-', label='$9x_2 = 40$')

# 가능 해 영역 색칠하기
# 교점 계산
x1_max = 40/3
x2_intersect1 = (3 * x1_max - 20) / 9

vertices = np.array([
    [0, 0],
    [20/3, 0],
    [x1_max, x2_intersect1],
    [x1_max, 40/9],
    [0, 40/9]
])
polygon = Polygon(vertices, alpha=0.3, color='skyblue')
plt.gca().add_patch(polygon)

plt.scatter(40/3, 40/9, color='black', s=80, zorder=5)
plt.annotate('(40/3, 40/9)', 
             (40/3, 40/9), 
             xytext=(-20, -20), 
             textcoords='offset points',
             fontsize=12)

plt.xlabel('$x_1$', fontsize=12)
plt.ylabel('$x_2$', fontsize=12)
plt.xlim(0, 15)
plt.ylim(0, 5)  # y축 범위 조정
plt.legend(loc='upper right')
plt.tight_layout(pad=1.1)
```
# 8.2-7

## a

### 초기 수송표

|             | 목적지 1 | 목적지 2 | 목적지 3 | 목적지 4 | 공급 |
| :---------- | :------- | :------- | :------- | :------- | :--- |
| **근원지 1** | 3        | 7        | 6        | 4        | **5** |
| **근원지 2** | 2        | 4        | 3        | 8        | **2** |
| **근원지 3** | 4        | 3        | 8        | 5        | **3** |
| **수요** | **3** | **3** | **2** | **2** |      |

### iteration


|             | 목적지 1       | 목적지 2 | 목적지 3 | 목적지 4 | 공급 |
| :---------- | :------------- | :------- | :------- | :------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | 7        | 6        | 4        | 2    |
| **근원지 2** | 2              | 4        | 3        | 8        | 2    |
| **근원지 3** | 4              | 3        | 8        | 5        | 3    |
| **수요** | 0              | **3** | **2** | **2** |      |


|             | 목적지 1       | 목적지 2       | 목적지 3 | 목적지 4 | 공급 |
| :---------- | :------------- | :------------- | :------- | :------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | **2** ($x_{12}=2$) | 6        | 4        | 0    |
| **근원지 2** | 2              | 4              | 3        | 8        | **2** |
| **근원지 3** | 4              | 3              | 8        | 5        | **3** |
| **수요** | 0              | 1              | **2** | **2** |      |


|             | 목적지 1       | 목적지 2       | 목적지 3 | 목적지 4 | 공급 |
| :---------- | :------------- | :------------- | :------- | :------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | **2** ($x_{12}=2$) | 6        | 4        | 0    |
| **근원지 2** | 2              | **1** ($x_{22}=1$) | 3        | 8        | 1    |
| **근원지 3** | 4              | 3              | 8        | 5        | **3** |
| **수요** | 0              | 0              | **2** | **2** |      |

|             | 목적지 1       | 목적지 2       | 목적지 3       | 목적지 4 | 공급 |
| :---------- | :------------- | :------------- | :------------- | :------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | **2** ($x_{12}=2$) | 6              | 4        | 0    |
| **근원지 2** | 2              | **1** ($x_{22}=1$) | **1** ($x_{23}=1$) | 8        | 0    |
| **근원지 3** | 4              | 3              | 8              | 5        | **3** |
| **수요** | 0              | 0              | 1              | **2** |      |

|             | 목적지 1       | 목적지 2       | 목적지 3       | 목적지 4 | 공급 |
| :---------- | :------------- | :------------- | :------------- | :------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | **2** ($x_{12}=2$) | 6              | 4        | 0    |
| **근원지 2** | 2              | **1** ($x_{22}=1$) | **1** ($x_{23}=1$) | 8        | 0    |
| **근원지 3** | 4              | 3              | **1** ($x_{33}=1$) | 5        | 2    |
| **수요** | 0              | 0              | 0              | **2** |      |

|             | 목적지 1       | 목적지 2       | 목적지 3       | 목적지 4       | 공급 |
| :---------- | :------------- | :------------- | :------------- | :------------- | :--- |
| **근원지 1** | **3** ($x_{11}=3$) | **2** ($x_{12}=2$) | 6              | 4              | 0    |
| **근원지 2** | 2              | **1** ($x_{22}=1$) | **1** ($x_{23}=1$) | 8              | 0    |
| **근원지 3** | 4              | 3              | **1** ($x_{33}=1$) | **2** ($x_{34}=2$) | 0    |
| **수요** | 0              | 0              | 0              | 0              |      |

### 초기 기저 가능해

- $x_{11} = 3$ (비용: $3 \times 3 = 9$)
- $x_{12} = 2$ (비용: $7 \times 2 = 14$)
- $x_{22} = 1$ (비용: $4 \times 1 = 4$)
- $x_{23} = 1$ (비용: $3 \times 1 = 3$)
- $x_{33} = 1$ (비용: $8 \times 1 = 8$)
- $x_{34} = 2$ (비용: $5 \times 2 = 10$)
- 다른 모든 $x_{ij} = 0$.

### 초기해의 총 수송 비용

$Z = (3 \times 3) + (7 \times 2) + (4 \times 1) + (3 \times 1) + (8 \times 1) + (5 \times 2)$

$Z = 9 + 14 + 4 + 3 + 8 + 10 = 48$

**iteration 1**

### 기저 변수

- $u_1 = 0$ 으로 설정.
- $x_{11}: u_1 + v_1 = c_{11} \Rightarrow 0 + v_1 = 3 \Rightarrow v_1 = 3$
- $x_{12}: u_1 + v_2 = c_{12} \Rightarrow 0 + v_2 = 7 \Rightarrow v_2 = 7$
- $x_{22}: u_2 + v_2 = c_{22} \Rightarrow u_2 + 7 = 4 \Rightarrow u_2 = -3$
- $x_{23}: u_2 + v_3 = c_{23} \Rightarrow -3 + v_3 = 3 \Rightarrow v_3 = 6$
- $x_{33}: u_3 + v_3 = c_{33} \Rightarrow u_3 + 6 = 8 \Rightarrow u_3 = 2$
- $x_{34}: u_3 + v_4 = c_{34} \Rightarrow 2 + v_4 = 5 \Rightarrow v_4 = 3$

∴ $u_1=0, u_2=-3, u_3=2$, $v_1=3, v_2=7, v_3=6, v_4=3$.

### 비기저 변수 제약식

* $x_{13}: c_{13} - u_1 - v_3 = 6 - 0 - 6 = 0$
* $x_{14}: c_{14} - u_1 - v_4 = 4 - 0 - 3 = 1$
* $x_{21}: c_{21} - u_2 - v_1 = 2 - (-3) - 3 = 2 - (-3+3) = 2$
* $x_{24}: c_{24} - u_2 - v_4 = 8 - (-3) - 3 = 8 - (-3+3) = 8$
* $x_{31}: c_{31} - u_3 - v_1 = 4 - 2 - 3 = -1$
* $x_{32}: c_{32} - u_3 - v_2 = 3 - 2 - 7 = -6$

- enter: $x_{32}$
- 경로: $x_{32} \rightarrow x_{33} \rightarrow x_{23} \rightarrow x_{22} \rightarrow x_{32}$
- $\theta = \min(x_{33}, x_{22}) = \min(1, 1) = 1$.

할당량

* $x_{32} = 0 + \theta = 1$
* $x_{33} = 1 - \theta = 0$
* $x_{23} = 1 + \theta = 2$
* $x_{22} = 1 - \theta = 0$ (탈락 변수)

- 기저해: $x_{11} = 3$, $x_{12} = 2$, $x_{23} = 2$, $x_{32} = 1$, $x_{33} = 0$, $x_{34} = 2$
- $Z = (3 \times 3) + (7 \times 2) + (3 \times 2) + (3 \times 1) + (8 \times 0) + (5 \times 2) = 42$.

**iteration 2**

### 기저 변수

* $u_1 = 0$
* $x_{11}: u_1 + v_1 = c_{11} \Rightarrow 0 + v_1 = 3 \Rightarrow v_1 = 3$
* $x_{12}: u_1 + v_2 = c_{12} \Rightarrow 0 + v_2 = 7 \Rightarrow v_2 = 7$
* $x_{32}: u_3 + v_2 = c_{32} \Rightarrow u_3 + 7 = 3 \Rightarrow u_3 = -4$
* $x_{33}: u_3 + v_3 = c_{33} \Rightarrow -4 + v_3 = 8 \Rightarrow v_3 = 12$
* $x_{34}: u_3 + v_4 = c_{34} \Rightarrow -4 + v_4 = 5 \Rightarrow v_4 = 9$
* $x_{23}: u_2 + v_3 = c_{23} \Rightarrow u_2 + 12 = 3 \Rightarrow u_2 = -9$

∴ $u_1=0, u_2=-9, u_3=-4$, $v_1=3, v_2=7, v_3=12, v_4=9$.

### 비기저 변수의 제약식

* $x_{13}: k_{13} = c_{13} - u_1 - v_3 = 6 - 0 - 12 = -6$
* $x_{14}: k_{14} = c_{14} - u_1 - v_4 = 4 - 0 - 9 = -5$
* $x_{21}: k_{21} = c_{21} - u_2 - v_1 = 2 - (-9) - 3 = 2 + 9 - 3 = 8$
* $x_{22}: k_{22} = c_{22} - u_2 - v_2 = 4 - (-9) - 7 = 4 + 9 - 7 = 6$
* $x_{24}: k_{24} = c_{24} - u_2 - v_4 = 8 - (-9) - 9 = 8 + 9 - 9 = 8$
* $x_{31}: k_{31} = c_{31} - u_3 - v_1 = 4 - (-4) - 3 = 4 + 4 - 3 = 5$

- enter: $x_{13}$
- 경로: $(1,3) \xrightarrow{+} (3,3) \xrightarrow{-} (3,2) \xrightarrow{+} (1,2) \xrightarrow{-} (1,3)$
- $\theta = \min(x_{33}, x_{12}) = \min(0, 2) = 0$.

할당량

* $x_{13} = 0 + 0 = 0$
* $x_{33} = 0 - 0 = 0$ (탈락 변수)
* $x_{32} = 1 + 0 = 1$
* $x_{12} = 2 - 0 = 2$

- 기저해: $x_{11}=3, x_{12}=2, x_{13}=0, x_{23}=2, x_{32}=1, x_{34}=2$.
- $Z = (3 \times 3) + (7 \times 2) + (6 \times 0) + (3 \times 2) + (3 \times 1) + (5 \times 2) = 9 + 14 + 0 + 6 + 3 + 10 = 42$.

**iteration 3**

### 기저 변수

* $u_1 = 0$ 으로 설정
* $x_{11}: u_1 + v_1 = c_{11} \Rightarrow 0 + v_1 = 3 \Rightarrow v_1 = 3$
* $x_{12}: u_1 + v_2 = c_{12} \Rightarrow 0 + v_2 = 7 \Rightarrow v_2 = 7$
* $x_{13}: u_1 + v_3 = c_{13} \Rightarrow 0 + v_3 = 6 \Rightarrow v_3 = 6$
* $x_{23}: u_2 + v_3 = c_{23} \Rightarrow u_2 + 6 = 3 \Rightarrow u_2 = -3$
* $x_{32}: u_3 + v_2 = c_{32} \Rightarrow u_3 + 7 = 3 \Rightarrow u_3 = -4$
* $x_{34}: u_3 + v_4 = c_{34} \Rightarrow -4 + v_4 = 5 \Rightarrow v_4 = 9$

∴ $u_1=0, u_2=-3, u_3=-4$, $v_1=3, v_2=7, v_3=6, v_4=9$.

### 비기저 변수 제약식

* $x_{14}: k_{14} = c_{14} - u_1 - v_4 = 4 - 0 - 9 = -5$
* $x_{21}: k_{21} = c_{21} - u_2 - v_1 = 2 - (-3) - 3 = 2 + 3 - 3 = 2$
* $x_{22}: k_{22} = c_{22} - u_2 - v_2 = 4 - (-3) - 7 = 4 + 3 - 7 = 0$
* $x_{24}: k_{24} = c_{24} - u_2 - v_4 = 8 - (-3) - 9 = 8 + 3 - 9 = 2$
* $x_{31}: k_{31} = c_{31} - u_3 - v_1 = 4 - (-4) - 3 = 4 + 4 - 3 = 5$
* $x_{33}: k_{33} = c_{33} - u_3 - v_3 = 8 - (-4) - 6 = 8 + 4 - 6 = 6$

- enter: $x_{14}$
- 경로: $(1,4) \xrightarrow{+} (3,4) \xrightarrow{-} (3,2) \xrightarrow{+} (1,2) \xrightarrow{-} (1,4)$
- $\theta = \min(x_{34}, x_{12}) = \min(2, 2) = 2$.

할당량

* $x_{14} = 0 + 2 = 2$
* $x_{34} = 2 - 2 = 0$ (탈락 변수)
* $x_{32} = 1 + 2 = 3$
* $x_{12} = 2 - 2 = 0$

- 기저해: $x_{11}=3, x_{12}=0, x_{13}=0, x_{14}=2, x_{23}=2, x_{32}=3$.
- $Z = (3 \times 3) + (7 \times 0) + (6 \times 0) + (4 \times 2) + (3 \times 2) + (3 \times 3) = 32$

**iteration 4**

### 기저 변수

* $u_1 = 0$ 으로 설정.
* $x_{11}: u_1 + v_1 = c_{11} \Rightarrow 0 + v_1 = 3 \Rightarrow v_1 = 3$
* $x_{12}: u_1 + v_2 = c_{12} \Rightarrow 0 + v_2 = 7 \Rightarrow v_2 = 7$
* $x_{13}: u_1 + v_3 = c_{13} \Rightarrow 0 + v_3 = 6 \Rightarrow v_3 = 6$
* $x_{14}: u_1 + v_4 = c_{14} \Rightarrow 0 + v_4 = 4 \Rightarrow v_4 = 4$
* $x_{23}: u_2 + v_3 = c_{23} \Rightarrow u_2 + 6 = 3 \Rightarrow u_2 = -3$
* $x_{32}: u_3 + v_2 = c_{32} \Rightarrow u_3 + 7 = 3 \Rightarrow u_3 = -4$

∴ $u_1=0, u_2=-3, u_3=-4$, $v_1=3, v_2=7, v_3=6, v_4=4$.

### 비기저 변수 제약식

* $x_{21}: k_{21} = c_{21} - u_2 - v_1 = 2 - (-3) - 3 = 2$
* $x_{22}: k_{22} = c_{22} - u_2 - v_2 = 4 - (-3) - 7 = 0$
* $x_{24}: k_{24} = c_{24} - u_2 - v_4 = 8 - (-3) - 4 = 7$
* $x_{31}: k_{31} = c_{31} - u_3 - v_1 = 4 - (-4) - 3 = 5$
* $x_{33}: k_{33} = c_{33} - u_3 - v_3 = 8 - (-4) - 6 = 6$
* $x_{34}: k_{34} = c_{34} - u_3 - v_4 = 5 - (-4) - 4 = 5$

모든 $k_{ij} \ge 0$ 이므로, 현재 해가 최적.

* $x_{11} = 3$
* $x_{12} = 0$
* $x_{13} = 0$
* $x_{14} = 2$
* $x_{23} = 2$
* $x_{32} = 3$
* 다른 모든 $x_{ij} = 0$.

$Z = 9 + 8 + 6 + 9 = 32$.

# 8.4-5

| 피할당인 | 과업 1 | 과업 2 | 과업 3 | 과업 4 |
| :------- | :----- | :----- | :----- | :----- |
| **A** | 4      | 1      | 0      | 1      |
| **B** | 1      | 3      | 4      | 0      |
| **C** | 3      | 2      | 1      | 3      |
| **D** | 2      | 2      | 3      | 0      |

| 피할당인 | 과업 1 | 과업 2 | 과업 3 | 과업 4 |
| :------- | :----- | :----- | :----- | :----- |
| **A** | 4      | 1      | 0      | 1      |
| **B** | 1      | 3      | 4      | 0      |
| **C** | 2      | 1      | 0      | 2      |
| **D** | 2      | 2      | 3      | 0      |

| 피할당인 | 과업 1 | 과업 2 | 과업 3 | 과업 4 |
| :------- | :----- | :----- | :----- | :----- |
| **A** | 3      | 0      | 0      | 1      |
| **B** | 0      | 2      | 4      | 0      |
| **C** | 1      | 0      | 0      | 2      |
| **D** | 1      | 1      | 3      | 0      |

**최적 할당 및 총비용:**

* A -> 과업 2
* B -> 과업 1
* C -> 과업 3
* D -> 과업 4

Z = 1 + 1 + 1 + 0 = 3
